import { SelectQueryBuilder, InsertIntoQueryBuilder, UpdateQueryBuilder, DeleteFromQueryBuilder, literal } from 'models/sql-builder'
import { schemas } from '../schemas'

export const attackArtQueryBuilder = new SelectQueryBuilder("attacks", "attack")
export const artsQueryBuilder = new SelectQueryBuilder("arts", "art")
attackArtQueryBuilder.select("name_prefix_art")
attackArtQueryBuilder.select("name")
attackArtQueryBuilder.select("id", "text")
attackArtQueryBuilder.select("title")
attackArtQueryBuilder.select("resume_description")
attackArtQueryBuilder.select("description")
attackArtQueryBuilder.select("banner")
attackArtQueryBuilder.select("damage")
attackArtQueryBuilder.select("breath")
attackArtQueryBuilder.select("blood")
attackArtQueryBuilder.select("intents")
attackArtQueryBuilder.select("updated_at")
attackArtQueryBuilder.where("attack.guild_id", { required: true, validator: schemas.discord_id() })
attackArtQueryBuilder.where("attack.art_id", { required: true, validator: schemas.id() })
attackArtQueryBuilder.orderBy("id")
attackArtQueryBuilder.agg()

artsQueryBuilder.select("name")
artsQueryBuilder.select("type")
artsQueryBuilder.select("id", "text")
artsQueryBuilder.select("description")
artsQueryBuilder.select("banner")
artsQueryBuilder.select("guild_id", "text")
artsQueryBuilder.select("updated_at")
artsQueryBuilder.where("art.guild_id", { required: true, validator: schemas.discord_id(), converter: "text" })
artsQueryBuilder.where("art.type", { required: false, validator: schemas.art_type() })
artsQueryBuilder.orderBy("id")

export const artQueryBuilder = new SelectQueryBuilder("arts", "art")
artQueryBuilder.select("name")
artQueryBuilder.select("type")
artQueryBuilder.select("id", "text")
artQueryBuilder.select("description")
artQueryBuilder.select("banner")
artQueryBuilder.select("guild_id")
artQueryBuilder.select("updated_at")
artQueryBuilder.where("art.guild_id", { required: true, validator: schemas.discord_id(), converter: "text" })
artQueryBuilder.where("art.id", { required: true, validator: schemas.id(), converter: "text" })
artQueryBuilder.limit(1)

artsQueryBuilder.include("attacks", attackArtQueryBuilder, {
  "attack.guild_id": literal("art.guild_id"),
  "attack.art_id": literal("art.id")
})
artQueryBuilder.include("attacks", attackArtQueryBuilder, {
  "attack.guild_id": literal("art.guild_id"),
  "attack.art_id": literal("art.id")
})

export const artInsertBuilder = new InsertIntoQueryBuilder("arts")
artInsertBuilder.select("name")
artInsertBuilder.select("type")
artInsertBuilder.select("id", "text")
artInsertBuilder.select("description")
artInsertBuilder.select("banner")
artInsertBuilder.select("guild_id")
artInsertBuilder.select("updated_at")
artInsertBuilder.column("name", { validator: schemas.name(), required: true })
artInsertBuilder.column("key", { validator: schemas.key(), required: true })
artInsertBuilder.column("guild_id", { validator: schemas.discord_id(), required: true })
artInsertBuilder.column("type", { validator: schemas.art_type(), required: true })
artInsertBuilder.column("description", { validator: schemas.description() })
artInsertBuilder.column("banner", { validator: schemas.banner() })

export const artUpdateQueryBuilder = new UpdateQueryBuilder("arts", "art")
artUpdateQueryBuilder.select("name")
artUpdateQueryBuilder.select("guild_id")
artUpdateQueryBuilder.select("id", "text")
artUpdateQueryBuilder.select("type")
artUpdateQueryBuilder.select("description")
artUpdateQueryBuilder.select("banner")
artUpdateQueryBuilder.select("updated_at")
artUpdateQueryBuilder.where("art.guild_id", { validator: schemas.discord_id(), required: true })
artUpdateQueryBuilder.where("art.id", { validator: schemas.id(), required: true })
artUpdateQueryBuilder.column("name", { validator: schemas.name() })
artUpdateQueryBuilder.column("key", { validator: schemas.key() })
artUpdateQueryBuilder.column("type", { validator: schemas.art_type() })
artUpdateQueryBuilder.column("description", { validator: schemas.description() })
artUpdateQueryBuilder.column("banner", { validator: schemas.banner() })
artUpdateQueryBuilder.column("updated_at", { required: true })

artUpdateQueryBuilder.include("attacks", attackArtQueryBuilder, {
  "attack.guild_id": literal("art.guild_id"),
  "attack.art_id": literal("art.id")
})

export const artDelQueryBuilder = new DeleteFromQueryBuilder("arts", "art")
artDelQueryBuilder.select("name")
artDelQueryBuilder.select("type")
artDelQueryBuilder.select("id", "text")
artDelQueryBuilder.select("description")
artDelQueryBuilder.select("banner")
artDelQueryBuilder.select("guild_id")
artDelQueryBuilder.select("updated_at")
artDelQueryBuilder.where("art.guild_id", { validator: schemas.discord_id(), required: true, converter: "text" })
artDelQueryBuilder.where("art.id", { validator: schemas.id(), required: true, converter: "text" })

artDelQueryBuilder.include("attacks", attackArtQueryBuilder, {
  "attack.guild_id": literal("art.guild_id"),
  "attack.art_id": literal("art.id")
})