import { SelectQueryBuilder, InsertIntoQueryBuilder, UpdateQueryBuilder, DeleteFromQueryBuilder } from "models/sql-builder"
import { schemas } from "../schemas"

export const attacksQueryBuilder = new SelectQueryBuilder("attacks", "attack")
attacksQueryBuilder.select("name_prefix_art")
attacksQueryBuilder.select("name")
attacksQueryBuilder.select("guild_id")
attacksQueryBuilder.select("id", "text")
attacksQueryBuilder.select("art_id", "text")
attacksQueryBuilder.select("title")
attacksQueryBuilder.select("description")
attacksQueryBuilder.select("resume_description")
attacksQueryBuilder.select("banner")
attacksQueryBuilder.select("damage")
attacksQueryBuilder.select("breath")
attacksQueryBuilder.select("blood")
attacksQueryBuilder.select("intents")
attacksQueryBuilder.select("updated_at")
attacksQueryBuilder.where("attack.guild_id", { validator: schemas.discord_id(), required: true })
attacksQueryBuilder.where("attack.art_id", { validator: schemas.id(), required: false })

export const attackQueryBuilder = new SelectQueryBuilder("attacks", "attack")
attackQueryBuilder.select("name_prefix_art")
attackQueryBuilder.select("name")
attackQueryBuilder.select("guild_id")
attackQueryBuilder.select("id", "text")
attackQueryBuilder.select("art_id", "text")
attackQueryBuilder.select("title")
attackQueryBuilder.select("description")
attackQueryBuilder.select("resume_description")
attackQueryBuilder.select("banner")
attackQueryBuilder.select("damage")
attackQueryBuilder.select("breath")
attackQueryBuilder.select("blood")
attackQueryBuilder.select("intents")
attackQueryBuilder.select("updated_at")
attackQueryBuilder.where("attack.guild_id", { validator: schemas.discord_id(), required: true })
attackQueryBuilder.where("attack.id", { validator: schemas.id(), required: true })
attackQueryBuilder.limit(1)

export const attackInsertQueryBuilder = new InsertIntoQueryBuilder("attacks")
attackInsertQueryBuilder.select("name_prefix_art")
attackInsertQueryBuilder.select("name")
attackInsertQueryBuilder.select("guild_id")
attackInsertQueryBuilder.select("id", "text")
attackInsertQueryBuilder.select("art_id", "text")
attackInsertQueryBuilder.select("title")
attackInsertQueryBuilder.select("description")
attackInsertQueryBuilder.select("resume_description")
attackInsertQueryBuilder.select("banner")
attackInsertQueryBuilder.select("damage")
attackInsertQueryBuilder.select("breath")
attackInsertQueryBuilder.select("blood")
attackInsertQueryBuilder.select("intents")
attackInsertQueryBuilder.select("updated_at")
attackInsertQueryBuilder.column("name_prefix_art", { validator: schemas.name_prefix_art() })
attackInsertQueryBuilder.column("name", { validator: schemas.name(), required: true })
attackInsertQueryBuilder.column("key", { validator: schemas.key(), required: true })
attackInsertQueryBuilder.column("guild_id", { validator: schemas.discord_id(), required: true })
attackInsertQueryBuilder.column("art_id", { validator: schemas.id(), required: true })
attackInsertQueryBuilder.column("title", { validator: schemas.title() })
attackInsertQueryBuilder.column("description", { validator: schemas.description() })
attackInsertQueryBuilder.column("resume_description", { validator: schemas.resume_description() })
attackInsertQueryBuilder.column("banner", { validator: schemas.banner() })
attackInsertQueryBuilder.column("damage", { validator: schemas.damage() })
attackInsertQueryBuilder.column("breath", { validator: schemas.breath() })
attackInsertQueryBuilder.column("blood", { validator: schemas.blood() })
attackInsertQueryBuilder.column("intents", { validator: schemas.intents() })

export const attackUpdateQueryBuilder = new UpdateQueryBuilder("DeleteFromQueryBuilder", "attack")
attackUpdateQueryBuilder.select("name_prefix_art")
attackUpdateQueryBuilder.select("name")
attackUpdateQueryBuilder.select("guild_id")
attackUpdateQueryBuilder.select("id", "text")
attackUpdateQueryBuilder.select("art_id", "text")
attackUpdateQueryBuilder.select("title")
attackUpdateQueryBuilder.select("description")
attackUpdateQueryBuilder.select("resume_description")
attackUpdateQueryBuilder.select("banner")
attackUpdateQueryBuilder.select("damage")
attackUpdateQueryBuilder.select("breath")
attackUpdateQueryBuilder.select("blood")
attackUpdateQueryBuilder.select("intents")
attackUpdateQueryBuilder.select("updated_at")
attackUpdateQueryBuilder.where("attack.guild_id", { validator: schemas.discord_id(), required: true})
attackUpdateQueryBuilder.where("attack.id", { validator: schemas.id(), required: true })
attackUpdateQueryBuilder.column("name_prefix_art", { validator: schemas.name_prefix_art() })
attackUpdateQueryBuilder.column("name", { validator: schemas.name(), required: true })
attackUpdateQueryBuilder.column("key", { validator: schemas.key(), required: true })
attackUpdateQueryBuilder.column("title", { validator: schemas.title() })
attackUpdateQueryBuilder.column("description", { validator: schemas.description() })
attackUpdateQueryBuilder.column("resume_description", { validator: schemas.resume_description() })
attackUpdateQueryBuilder.column("banner", { validator: schemas.banner() })
attackUpdateQueryBuilder.column("damage", { validator: schemas.damage() })
attackUpdateQueryBuilder.column("breath", { validator: schemas.breath() })
attackUpdateQueryBuilder.column("blood", { validator: schemas.blood() })
attackUpdateQueryBuilder.column("intents", { validator: schemas.intents() })
attackUpdateQueryBuilder.column("updated_at", { required: true })

export const attackDelQueryBuilder = new DeleteFromQueryBuilder("attacks", "attack")
attackDelQueryBuilder.select("name_prefix_art")
attackDelQueryBuilder.select("name")
attackDelQueryBuilder.select("guild_id")
attackDelQueryBuilder.select("id", "text")
attackDelQueryBuilder.select("art_id", "text")
attackDelQueryBuilder.select("title")
attackDelQueryBuilder.select("description")
attackDelQueryBuilder.select("resume_description")
attackDelQueryBuilder.select("banner")
attackDelQueryBuilder.select("damage")
attackDelQueryBuilder.select("breath")
attackDelQueryBuilder.select("blood")
attackDelQueryBuilder.select("intents")
attackDelQueryBuilder.select("updated_at")
attackDelQueryBuilder.where("attack.guild_id", { validator: schemas.discord_id(), required: true })
attackDelQueryBuilder.where("attack.id", { validator: schemas.id(), required: true })