import { SelectQueryBuilder, InsertIntoQueryBuilder, DeleteFromQueryBuilder, literal } from 'models/sql-builder'
import { attackArtQueryBuilder } from './arts'
import { schemas } from '../schemas'

export const guildQueryBuilder = new SelectQueryBuilder("guilds", "guild")
export const artQueryBuilder = new SelectQueryBuilder("arts", "art")
guildQueryBuilder.select("id")
guildQueryBuilder.select("default_player_life")
guildQueryBuilder.select("default_player_breath")
guildQueryBuilder.select("default_player_blood")
guildQueryBuilder.select("default_player_resistance")
guildQueryBuilder.select("default_player_force")
guildQueryBuilder.select("default_player_velocity")
guildQueryBuilder.where("guild.id", { validator: schemas.discord_id(), required : true})
guildQueryBuilder.limit(1)
artQueryBuilder.select("name")
artQueryBuilder.select("type")
artQueryBuilder.select("id", "text")
artQueryBuilder.select("description")
artQueryBuilder.select("banner")
artQueryBuilder.select("guild_id")
artQueryBuilder.select("updated_at")
artQueryBuilder.where("art.guild_id", { validator: schemas.discord_id(), required: true })
artQueryBuilder.agg()

guildQueryBuilder.include("arts", artQueryBuilder, { "art.guild_id": literal("guild.id") })
artQueryBuilder.include("attacks", attackArtQueryBuilder, { "attack.guild_id": literal("art.guild_id"), "attack.art_id": literal("art.id") })

export const guildInsertQueryBuilder = new InsertIntoQueryBuilder("guilds")
guildInsertQueryBuilder.select("id")
guildInsertQueryBuilder.select("default_player_life")
guildInsertQueryBuilder.select("default_player_breath")
guildInsertQueryBuilder.select("default_player_blood")
guildInsertQueryBuilder.select("default_player_resistance")
guildInsertQueryBuilder.select("default_player_force")
guildInsertQueryBuilder.select("default_player_velocity")
guildInsertQueryBuilder.column("id", { validator: schemas.discord_id(), required: true })
guildInsertQueryBuilder.column("default_player_life", { validator: schemas.default_player_life() })
guildInsertQueryBuilder.column("default_player_breath", { validator: schemas.default_player_breath() })
guildInsertQueryBuilder.column("default_player_blood", { validator: schemas.default_player_blood() })
guildInsertQueryBuilder.column("default_player_resistance", { validator: schemas.default_player_resistance() })
guildInsertQueryBuilder.column("default_player_force", { validator: schemas.default_player_force() })
guildInsertQueryBuilder.column("default_player_velocity", { validator: schemas.default_player_velocity() })

export const guildDeleteQueryBuilder = new DeleteFromQueryBuilder("guilds", "guild")
guildDeleteQueryBuilder.select("id")
guildDeleteQueryBuilder.select("default_player_life")
guildDeleteQueryBuilder.select("default_player_breath")
guildDeleteQueryBuilder.select("default_player_blood")
guildDeleteQueryBuilder.select("default_player_resistance")
guildDeleteQueryBuilder.select("default_player_force")
guildDeleteQueryBuilder.select("default_player_velocity")
guildDeleteQueryBuilder.where("guild.id", { validator: schemas.discord_id(), required : true})
guildDeleteQueryBuilder.include("arts", artQueryBuilder, { "art.guild_id": literal("guild.id") })