import { DeleteFromQueryBuilder, InsertIntoQueryBuilder, SelectQueryBuilder, UpdateQueryBuilder } from "models/sql-builder"
import { schemas } from "../schemas"

export const itemsQueryBuilder = new SelectQueryBuilder("items", "item")
itemsQueryBuilder.where("item.guild_id", { validator: schemas.discord_id(), required: true })
itemsQueryBuilder.select("name")
itemsQueryBuilder.select("id", "text")
itemsQueryBuilder.select("art_id", "text")
itemsQueryBuilder.select("guild_id")
itemsQueryBuilder.select("description")
itemsQueryBuilder.select("banner")
itemsQueryBuilder.select("stack")
itemsQueryBuilder.select("usable")
itemsQueryBuilder.select("equip")
itemsQueryBuilder.select("updated_at")

export const itemQueryBuilder = new SelectQueryBuilder("items", "item")
itemQueryBuilder.where("item.guild_id", { validator: schemas.discord_id(), required: true })
itemQueryBuilder.where("item.id", { validator: schemas.id(), required: true, converter: "text" })
itemQueryBuilder.select("name")
itemQueryBuilder.select("id", "text")
itemQueryBuilder.select("art_id", "text")
itemQueryBuilder.select("guild_id")
itemQueryBuilder.select("description")
itemQueryBuilder.select("banner")
itemQueryBuilder.select("stack")
itemQueryBuilder.select("usable")
itemQueryBuilder.select("equip")
itemQueryBuilder.select("updated_at")
itemQueryBuilder.limit(1)

export const itemInsertQueryBuilder = new InsertIntoQueryBuilder("items")
itemInsertQueryBuilder.select("name")
itemInsertQueryBuilder.select("id", "text")
itemInsertQueryBuilder.select("art_id", "text")
itemInsertQueryBuilder.select("guild_id")
itemInsertQueryBuilder.select("description")
itemInsertQueryBuilder.select("banner")
itemInsertQueryBuilder.select("stack")
itemInsertQueryBuilder.select("usable")
itemInsertQueryBuilder.select("equip")
itemInsertQueryBuilder.select("updated_at")
itemInsertQueryBuilder.column("name", { validator: schemas.name(), required: true })
itemInsertQueryBuilder.column("key", { validator: schemas.key(), required: true })
itemInsertQueryBuilder.column("guild_id", { validator: schemas.discord_id(), required: true })
itemInsertQueryBuilder.column("art_id", { validator: schemas.id() })
itemInsertQueryBuilder.column("description", { validator: schemas.description() })
itemInsertQueryBuilder.column("banner", { validator: schemas.banner() })
itemInsertQueryBuilder.column("stack", { validator: schemas.stack() })
itemInsertQueryBuilder.column("usable", { validator: schemas.usable() })

export const itemUpdateQueryBuilder = new UpdateQueryBuilder("items", "item")
itemUpdateQueryBuilder.where("item.guild_id", { validator: schemas.discord_id(), required: true })
itemUpdateQueryBuilder.where("item.id", { validator: schemas.id(), required: true, converter: "text" })
itemUpdateQueryBuilder.select("name")
itemUpdateQueryBuilder.select("id", "text")
itemUpdateQueryBuilder.select("art_id", "text")
itemUpdateQueryBuilder.select("guild_id")
itemUpdateQueryBuilder.select("description")
itemUpdateQueryBuilder.select("banner")
itemUpdateQueryBuilder.select("stack")
itemUpdateQueryBuilder.select("usable")
itemUpdateQueryBuilder.select("equip")
itemUpdateQueryBuilder.select("updated_at")
itemUpdateQueryBuilder.column("name", { validator: schemas.name() })
itemUpdateQueryBuilder.column("key", { validator: schemas.key() })
itemUpdateQueryBuilder.column("art_id", { validator: schemas.id() })
itemUpdateQueryBuilder.column("description", { validator: schemas.description() })
itemUpdateQueryBuilder.column("banner", { validator: schemas.banner() })
itemUpdateQueryBuilder.column("stack", { validator: schemas.stack() })
itemUpdateQueryBuilder.column("usable", { validator: schemas.usable() })

export const itemDeleteQueryBuilder = new DeleteFromQueryBuilder("items", "item")
itemDeleteQueryBuilder.where("item.guild_id", { validator: schemas.discord_id(), required: true })
itemDeleteQueryBuilder.where("item.id", { validator: schemas.id(), required: true, converter: "text" })
itemDeleteQueryBuilder.select("name")
itemDeleteQueryBuilder.select("id", "text")
itemDeleteQueryBuilder.select("art_id", "text")
itemDeleteQueryBuilder.select("guild_id")
itemDeleteQueryBuilder.select("description")
itemDeleteQueryBuilder.select("banner")
itemDeleteQueryBuilder.select("stack")
itemDeleteQueryBuilder.select("usable")
itemDeleteQueryBuilder.select("equip")
itemDeleteQueryBuilder.select("updated_at")