import { DeleteFromQueryBuilder, InsertIntoQueryBuilder, SelectQueryBuilder, UpdateQueryBuilder } from "models/sql-builder"
import { schemas } from "models/schemas"

const localsQueryBuilder = new SelectQueryBuilder("locations", "local")
localsQueryBuilder.where("local.guild_id", { validator: schemas.discord_id(), required: true })
localsQueryBuilder.select("name")
localsQueryBuilder.select("guild_id")
localsQueryBuilder.select("id")
localsQueryBuilder.select("location_id")
localsQueryBuilder.select("description")
localsQueryBuilder.select("resume_description")
localsQueryBuilder.select("access")
localsQueryBuilder.select("banner")
localsQueryBuilder.select("updated_at")

const localInsertQueryBuilder = new InsertIntoQueryBuilder("locations")
localInsertQueryBuilder.select("name")
localInsertQueryBuilder.select("guild_id")
localInsertQueryBuilder.select("id", "text")
localInsertQueryBuilder.select("location_id")
localInsertQueryBuilder.select("description")
localInsertQueryBuilder.select("resume_description")
localInsertQueryBuilder.select("access")
localInsertQueryBuilder.select("banner")
localInsertQueryBuilder.select("updated_at")
localInsertQueryBuilder.column("name", { validator: schemas.name(), required: true })
localInsertQueryBuilder.column("key", { validator: schemas.key(), required: true })
localInsertQueryBuilder.column("guild_id", { validator: schemas.discord_id(), required: true })
localInsertQueryBuilder.column("id", { validator: schemas.discord_id(), required: true })
localInsertQueryBuilder.column("location_id", { validator: schemas.discord_id() })
localInsertQueryBuilder.column("description", { validator: schemas.description() })
localInsertQueryBuilder.column("resume_description", { validator: schemas.resume_description() })
localInsertQueryBuilder.column("access", { validator: schemas.access() })
localInsertQueryBuilder.column("banner", { validator: schemas.banner() })

const localUpdateQueryBuilder = new UpdateQueryBuilder("locations", "local")
localUpdateQueryBuilder.where("local.guild_id", { validator: schemas.discord_id(), required: true })
localUpdateQueryBuilder.where("local.id", { validator: schemas.discord_id(), required: true })
localUpdateQueryBuilder.select("name")
localUpdateQueryBuilder.select("guild_id")
localUpdateQueryBuilder.select("id")
localUpdateQueryBuilder.select("location_id")
localUpdateQueryBuilder.select("description")
localUpdateQueryBuilder.select("resume_description")
localUpdateQueryBuilder.select("access")
localUpdateQueryBuilder.select("banner")
localUpdateQueryBuilder.select("updated_at")
localInsertQueryBuilder.column("name", { validator: schemas.name() })
localInsertQueryBuilder.column("key", { validator: schemas.key() })
localInsertQueryBuilder.column("guild_id", { validator: schemas.discord_id() })
localInsertQueryBuilder.column("id", { validator: schemas.discord_id() })
localInsertQueryBuilder.column("location_id", { validator: schemas.discord_id() })
localInsertQueryBuilder.column("description", { validator: schemas.description() })
localInsertQueryBuilder.column("resume_description", { validator: schemas.resume_description() })
localInsertQueryBuilder.column("access", { validator: schemas.access() })
localInsertQueryBuilder.column("banner", { validator: schemas.banner() })
localInsertQueryBuilder.column("updated_at", { required: true })

const localDeleteQueryBuilder = new DeleteFromQueryBuilder("locations", "local")
localDeleteQueryBuilder.where("local.guild_id", { validator: schemas.discord_id(), required: true })
localDeleteQueryBuilder.where("local.id", { validator: schemas.discord_id(), required: true })
localDeleteQueryBuilder.select("name")
localDeleteQueryBuilder.select("guild_id")
localDeleteQueryBuilder.select("id")
localDeleteQueryBuilder.select("location_id")
localDeleteQueryBuilder.select("description")
localDeleteQueryBuilder.select("resume_description")
localDeleteQueryBuilder.select("access")
localDeleteQueryBuilder.select("banner")
localDeleteQueryBuilder.select("updated_at")