import { SelectQueryBuilder, InsertIntoQueryBuilder, UpdateQueryBuilder, DeleteFromQueryBuilder, literal } from "models/sql-builder"
import { schemas } from "../schemas"

export const playerQueryBuilder = new SelectQueryBuilder("players", "player")
playerQueryBuilder.select("name")
playerQueryBuilder.select("surname")
playerQueryBuilder.select("guild_id")
playerQueryBuilder.select("id")
playerQueryBuilder.select("type")
playerQueryBuilder.select("location_id")
playerQueryBuilder.select("life")
playerQueryBuilder.select("breath")
playerQueryBuilder.select("blood")
playerQueryBuilder.select("exp")
playerQueryBuilder.select("force")
playerQueryBuilder.select("resistance")
playerQueryBuilder.select("velocity")
playerQueryBuilder.select("appearance")
playerQueryBuilder.select("updated_at")
playerQueryBuilder.partial(1)
playerQueryBuilder.limit(1)

export const playerInventoryQueryBuilder = new SelectQueryBuilder("inventory", "inventory")
playerInventoryQueryBuilder.select("item_id", "text")
playerInventoryQueryBuilder.select("stack")
playerInventoryQueryBuilder.select("created_at")
playerInventoryQueryBuilder.where("inventory.player_id", { validator: schemas.discord_id(), required: true })
playerInventoryQueryBuilder.where("inventory.guild_id", { validator: schemas.discord_id(), required: true })

export const playerArtsQueryBuilder = new SelectQueryBuilder("player_arts", "plart")
export const playerAttacksQueryBuilder = new SelectQueryBuilder("player_attacks", "plattack")
playerQueryBuilder.include("arts", playerArtsQueryBuilder, { "plart.guild_id": literal("player.guild_id"), "plart.player_id": literal("player.id") })
playerQueryBuilder.include("attacks", playerAttacksQueryBuilder, { "plattack.guild_id": literal("player.guild_id"), "plattack.player_id": literal("player.id") })
playerAttacksQueryBuilder.select("attack_id", "text")
playerArtsQueryBuilder.select("art_id", "text")

playerAttacksQueryBuilder.where("plattack.player_id", { validator: schemas.discord_id(), required: true })
playerAttacksQueryBuilder.where("plattack.guild_id", { validator: schemas.discord_id(), required: true })
playerArtsQueryBuilder.where("plart.player_id", { validator: schemas.discord_id(), required: true })
playerArtsQueryBuilder.where("plart.guild_id", { validator: schemas.discord_id(), required: true })
playerQueryBuilder.where("player.guild_id", { validator: schemas.discord_id(), required: true })
playerQueryBuilder.where("player.id", { validator: schemas.discord_id(), required: 'partial' })
playerQueryBuilder.where("player.surname", { validator: schemas.surname(), required: 'partial' })

playerAttacksQueryBuilder.agg()
playerArtsQueryBuilder.agg()

export const playerInsertQueryBuilder = new InsertIntoQueryBuilder("players")
playerInsertQueryBuilder.select("name")
playerInsertQueryBuilder.select("surname")
playerInsertQueryBuilder.select("guild_id")
playerInsertQueryBuilder.select("id")
playerInsertQueryBuilder.select("type")
playerInsertQueryBuilder.select("location_id")
playerInsertQueryBuilder.select("life")
playerInsertQueryBuilder.select("breath")
playerInsertQueryBuilder.select("blood")
playerInsertQueryBuilder.select("exp")
playerInsertQueryBuilder.select("force")
playerInsertQueryBuilder.select("resistance")
playerInsertQueryBuilder.select("velocity")
playerInsertQueryBuilder.select("appearance")
playerInsertQueryBuilder.select("updated_at")
playerInsertQueryBuilder.column("name", { validator: schemas.name(), required: true })
playerInsertQueryBuilder.column("surname", { validator: schemas.surname(), required: true })
playerInsertQueryBuilder.column("type", { validator: schemas.player_type(), required: true })
playerInsertQueryBuilder.column("id", { validator: schemas.discord_id(), required: true })
playerInsertQueryBuilder.column("guild_id", { validator: schemas.discord_id(), required: true })
playerInsertQueryBuilder.column("life", { validator: schemas.life() })
playerInsertQueryBuilder.column("breath", { validator: schemas.breath() })
playerInsertQueryBuilder.column("blood", { validator: schemas.blood() })
playerInsertQueryBuilder.column("exp", { validator: schemas.exp() })
playerInsertQueryBuilder.column("force", { validator: schemas.force() })
playerInsertQueryBuilder.column("resistance", { validator: schemas.resistance() })
playerInsertQueryBuilder.column("velocity", { validator: schemas.velocity() })
playerInsertQueryBuilder.column("appearance", { validator: schemas.appearance() })

export const playerUpdateQueryBuilder = new UpdateQueryBuilder("players", "player")
playerUpdateQueryBuilder.include("attacks", playerAttacksQueryBuilder, { "plattack.guild_id": literal("player.guild_id"), "plattack.player_id": literal("player.id") })
playerUpdateQueryBuilder.include("arts", playerArtsQueryBuilder, { "plart.guild_id": literal("player.guild_id"), "plart.player_id": literal("player.id") })
playerUpdateQueryBuilder.where("player.guild_id", { validator: schemas.discord_id(), required: true })
playerUpdateQueryBuilder.where("player.id", { validator: schemas.discord_id(), required: true })

playerUpdateQueryBuilder.select("name")
playerUpdateQueryBuilder.select("surname")
playerUpdateQueryBuilder.select("guild_id")
playerUpdateQueryBuilder.select("id")
playerUpdateQueryBuilder.select("type")
playerUpdateQueryBuilder.select("location_id")
playerUpdateQueryBuilder.select("life")
playerUpdateQueryBuilder.select("breath")
playerUpdateQueryBuilder.select("blood")
playerUpdateQueryBuilder.select("exp")
playerUpdateQueryBuilder.select("force")
playerUpdateQueryBuilder.select("resistance")
playerUpdateQueryBuilder.select("velocity")
playerUpdateQueryBuilder.select("appearance")
playerUpdateQueryBuilder.select("updated_at")
playerUpdateQueryBuilder.column("name", { validator: schemas.name() })
playerUpdateQueryBuilder.column("surname", { validator: schemas.surname() })
playerUpdateQueryBuilder.column("location_id", { validator: schemas.discord_id() })
playerUpdateQueryBuilder.column("life", { validator: schemas.life() })
playerUpdateQueryBuilder.column("breath", { validator: schemas.breath() })
playerUpdateQueryBuilder.column("blood", { validator: schemas.blood() })
playerUpdateQueryBuilder.column("exp", { validator: schemas.exp() })
playerUpdateQueryBuilder.column("force", { validator: schemas.force() })
playerUpdateQueryBuilder.column("resistance", { validator: schemas.resistance() })
playerUpdateQueryBuilder.column("velocity", { validator: schemas.velocity() })
playerUpdateQueryBuilder.column("appearance", { validator: schemas.appearance() })
playerUpdateQueryBuilder.column("updated_at", { required: true })

export const playerDeleteQueryBuilder = new DeleteFromQueryBuilder("players", "player")
playerDeleteQueryBuilder.include("attacks", playerAttacksQueryBuilder, { "plattack.guild_id": literal("player.guild_id"), "plattack.player_id": literal("player.id") })
playerDeleteQueryBuilder.include("arts", playerArtsQueryBuilder, { "plart.guild_id": literal("player.guild_id"), "plart.player_id": literal("player.id") })
playerDeleteQueryBuilder.where("player.guild_id", { validator: schemas.discord_id(), required: true })
playerDeleteQueryBuilder.where("player.id", { validator: schemas.discord_id(), required: true })
playerDeleteQueryBuilder.select("name")
playerDeleteQueryBuilder.select("surname")
playerDeleteQueryBuilder.select("guild_id")
playerDeleteQueryBuilder.select("id")
playerDeleteQueryBuilder.select("type")
playerDeleteQueryBuilder.select("location_id")
playerDeleteQueryBuilder.select("life")
playerDeleteQueryBuilder.select("breath")
playerDeleteQueryBuilder.select("blood")
playerDeleteQueryBuilder.select("exp")
playerDeleteQueryBuilder.select("force")
playerDeleteQueryBuilder.select("resistance")
playerDeleteQueryBuilder.select("velocity")
playerDeleteQueryBuilder.select("appearance")
playerDeleteQueryBuilder.select("updated_at")